# Generated by Django 3.2 on 2024-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
